In [1]:
from sklearn import naive_bayes

In [2]:
import numpy as np

In [3]:
df=np.loadtxt(r"C:\Users\Lenovo\Desktop\spambase.data.txt",dtype="str",delimiter=",")
df

array([['0', '0.64', '0.64', ..., '61', '278', '1'],
       ['0.21', '0.28', '0.5', ..., '101', '1028', '1'],
       ['0.06', '0', '0.71', ..., '485', '2259', '1'],
       ...,
       ['0.3', '0', '0.3', ..., '6', '118', '0'],
       ['0.96', '0', '0', ..., '5', '78', '0'],
       ['0', '0', '0.65', ..., '5', '40', '0']], dtype='<U7')

In [6]:
y=df[:,-1]

In [7]:
y=y.astype('int')
y.shape

(4601,)

In [8]:
x=df[:,:-1]
x.shape

(4601, 57)

In [9]:
x=x.astype('float')

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [12]:
nm=naive_bayes.MultinomialNB()

In [13]:
nm.fit(x_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [14]:
nm.score(x_test,y_test)*100

80.78175895765473

In [15]:
count=0
for i in range(len(x_test)):
    p=nm.predict([x_test[i]])
    if(p==y_test[i]):
        count+=1
print("Accuracy score is %.2f%%"%((count/len(x_test))*100))

Accuracy score is 80.78%


In [16]:
PREDICT_INDEX=69
p=nm.predict([x_test[PREDICT_INDEX]])
print("Actual result:",y_test[PREDICT_INDEX])
print("Predicted result:",p)

Actual result: 1
Predicted result: [0]


In [17]:
import pandas as pd

In [18]:
df=pd.read_csv(r"C:\Users\Lenovo\Desktop\SMSSpamCollection.txt",sep="\t",names=["status","messages"])
df.head()

status                                           messages
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
status      5572 non-null object
messages    5572 non-null object
dtypes: object(2)
memory usage: 87.1+ KB


In [20]:
df.index

RangeIndex(start=0, stop=5572, step=1)

In [21]:
df.head()

status                                           messages
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [22]:
df.loc[df['status']=='spam',"status"]=0
df.loc[df['status']=='ham',"status"]=1

In [23]:
df.head(2)

status                                           messages
0      1  Go until jurong point, crazy.. Available only ...
1      1                      Ok lar... Joking wif u oni...

In [24]:
y=df['status'].values
y

array([1, 1, 0, ..., 1, 1, 1], dtype=object)

In [25]:
x=df['messages']
x.head()

0    Go until jurong point, crazy.. Available only ...
1                        Ok lar... Joking wif u oni...
2    Free entry in 2 a wkly comp to win FA Cup fina...
3    U dun say so early hor... U c already then say...
4    Nah I don't think he goes to usf, he lives aro...
Name: messages, dtype: object

In [26]:
from sklearn.feature_extraction.text import CountVectorizer

In [27]:
arr=["Go until jurong point point","U dun say so early hor"]

In [28]:
count_vt=CountVectorizer()

In [29]:
a=count_vt.fit(arr)

In [30]:
tr_arr=count_vt.transform(arr)

In [31]:
tr_arr.toarray()

array([[0, 0, 1, 0, 1, 2, 0, 0, 1],
       [1, 1, 0, 1, 0, 0, 1, 1, 0]], dtype=int64)

In [32]:
count_vt.get_feature_names()

['dun', 'early', 'go', 'hor', 'jurong', 'point', 'say', 'so', 'until']

In [33]:
ct_vt=CountVectorizer()

In [34]:
a=ct_vt.fit(x)

In [35]:
obj_vt=ct_vt.transform(x)

In [36]:
arr_vt=obj_vt.toarray()
arr_vt

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [37]:
arr_vt.shape

(5572, 8713)

In [38]:
y=y.astype("int")
y

array([1, 1, 0, ..., 1, 1, 1])

In [39]:
x_train,x_test,y_train,y_test=train_test_split(arr_vt,y,test_size=0.2)

In [40]:
print(len(x_train),x_train.shape)

4457 (4457, 8713)


In [41]:
print(len(x_test),x_test.shape)

1115 (1115, 8713)


In [42]:
print(len(y_train),y_train.shape)

4457 (4457,)


In [43]:
print(len(y_test),y_test.shape)

1115 (1115,)


In [44]:
nbm=naive_bayes.MultinomialNB()

In [45]:
nbm.fit(x_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [46]:
count=0
for i in range(len(x_test)):
    p=nbm.predict([x_test[i]])
    if(y_test[i]==p):
        count+=1
print("Accuracy is %5.2f%%"%((count/len(x_test))*100))

Accuracy is 98.03%


In [47]:
nbm.score(x_test,y_test)

0.9802690582959641

In [48]:
# ct_vt.get_feature_names()

In [49]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [50]:
y

array([1, 1, 0, ..., 1, 1, 1])

In [51]:
x.head(2)

0    Go until jurong point, crazy.. Available only ...
1                        Ok lar... Joking wif u oni...
Name: messages, dtype: object

In [52]:
tfidf=TfidfVectorizer()

In [53]:
from sklearn.linear_model import LogisticRegression

In [54]:
from sklearn.datasets import load_iris

In [55]:
data=load_iris()
y=data['target']
y[:5]

array([0, 0, 0, 0, 0])

In [56]:
x=data['data']
x[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [57]:
llr=LogisticRegression()

In [58]:
from sklearn.model_selection import train_test_split

In [59]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [60]:
llr.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [61]:
PREDICT_INDEX=17
p=llr.predict([x_test[PREDICT_INDEX]])
print("Actual result is: ",y_test[PREDICT_INDEX])
print("Predicted result is: ",p)

Actual result is:  2
Predicted result is:  [2]


In [62]:
llr.score(x_test,y_test)

0.9333333333333333

In [63]:
count=0
for i in range(len(x_test)):
    p=llr.predict([x_test[i]])
    if(y_test[i]==p):
        count+=1
print("Accuracy score is %5.2f%%"%((count/len(x_test))*100))

Accuracy score is 93.33%
